// Command tools-gen reads docs/reference/tool-projection.json and renders
// docs/reference/tool-projection.md (human-readable). Eliminates drift
// between the structured tool-projection data and its rendered documentation.
//
// Derived views (like the "universal paths" matrix showing which tools read
// the same paths) are computed here from the source data rather than
// duplicated in the JSON.
//
// Invoked via `go generate ./internal/mount/...`.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const headerNote = `<!--
AUTO-GENERATED by cmd/tools-gen. Do not edit directly.
Edit docs/reference/tool-projection.json and run: go generate ./internal/mount/...
-->

`

func main() {
	repoRoot := findRepoRoot()
	jsonPath := filepath.Join(repoRoot, "docs", "reference", "tool-projection.json")
	mdPath := filepath.Join(repoRoot, "docs", "reference", "tool-projection.md")

	data, err := os.ReadFile(jsonPath)
	must(err)

	var doc projectionDoc
	must(json.Unmarshal(data, &doc))

	f, err := os.Create(mdPath)
	must(err)
	defer f.Close()

	render(f, &doc)
	fmt.Printf("wrote %s\n", mdPath)
}

func findRepoRoot() string {
	dir, err := os.Getwd()
	must(err)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fail("could not find go.mod from cwd")
		}
		dir = parent
	}
}

func must(err error) {
	if err != nil {
		fail(err.Error())
	}
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "tools-gen:", msg)
	os.Exit(1)
}

// --- JSON shape ---

type projectionDoc struct {
	SchemaVersion int                  `json:"$schema_version"`
	UpdatedAt     string               `json:"updated_at"`
	ScopeNotes    string               `json:"scope_notes"`
	KindsDefs     map[string]string    `json:"kinds_definitions"`
	Tools         map[string]toolEntry `json:"tools"`
	Watchlist     watchlistSection     `json:"watchlist"`
}

type toolEntry struct {
	DisplayName  string               `json:"display_name"`
	DocsHomepage string               `json:"docs_homepage"`
	Category     string               `json:"category"`
	Status       string               `json:"status"`
	CSAWInCode   bool                 `json:"csaw_in_code"`
	ScopeNotes   string               `json:"scope_notes"`
	Kinds        map[string]kindEntry `json:"kinds"`
}

type kindEntry struct {
	ProjectPaths []string `json:"project_paths,omitempty"`
	UserPaths    []string `json:"user_paths,omitempty"`
	Format       string   `json:"format,omitempty"`
	FilePattern  string   `json:"file_pattern,omitempty"`
	SchemaTopKey string   `json:"schema_top_level_key,omitempty"`
	Transports   []string `json:"transports,omitempty"`
	AuthTypes    []string `json:"auth_types,omitempty"`
	EnvVarSub    []string `json:"env_var_substitution,omitempty"`
	Notes        string   `json:"notes,omitempty"`
	Confidence   string   `json:"confidence,omitempty"`
}

type watchlistSection struct {
	Description string                `json:"description"`
	Tools       map[string]watchEntry `json:"tools"`
}

type watchEntry struct {
	DisplayName  string   `json:"display_name"`
	Status       string   `json:"status"`
	CSAWInCode   bool     `json:"csaw_in_code"`
	ScopeNotes   string   `json:"scope_notes"`
	ProjectPaths []string `json:"project_paths"`
	UserPaths    []string `json:"user_paths"`
	MCPKey       string   `json:"mcp_key"`
}

// --- rendering ---

func render(w io.Writer, doc *projectionDoc) {
	io.WriteString(w, headerNote)
	fmt.Fprintf(w, "# Tool Projection Reference\n\n")
	fmt.Fprintf(w, "**Schema version:** %d  ·  **Updated:** %s\n\n", doc.SchemaVersion, doc.UpdatedAt)
	fmt.Fprintf(w, "%s\n\n", doc.ScopeNotes)
	fmt.Fprintf(w, "Planning content (recommended additions, deferred tools) lives in [`../planning/projection-roadmap.md`](../planning/projection-roadmap.md).\n\n")

	renderInCodeSummary(w, doc)
	renderKinds(w, doc.KindsDefs)
	renderUniversalPaths(w, doc)
	renderTools(w, doc.Tools)
	renderWatchlist(w, &doc.Watchlist)
}

func renderInCodeSummary(w io.Writer, doc *projectionDoc) {
	fmt.Fprintln(w, "## Currently Projected by csaw")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Tools with `csaw_in_code: true` (consistency-tested against `ToolRegistry`):")
	fmt.Fprintln(w)
	var inCode []string
	for name, t := range doc.Tools {
		if t.CSAWInCode {
			inCode = append(inCode, name)
		}
	}
	for name, t := range doc.Watchlist.Tools {
		if t.CSAWInCode {
			inCode = append(inCode, name)
		}
	}
	sort.Strings(inCode)
	for _, name := range inCode {
		display := ""
		if t, ok := doc.Tools[name]; ok {
			display = t.DisplayName
		} else if t, ok := doc.Watchlist.Tools[name]; ok {
			display = t.DisplayName
		}
		fmt.Fprintf(w, "- **`%s`** — %s\n", name, display)
	}
	fmt.Fprintln(w)
}

func renderKinds(w io.Writer, kinds map[string]string) {
	if len(kinds) == 0 {
		return
	}
	fmt.Fprintln(w, "## Kinds")
	fmt.Fprintln(w)
	for _, name := range sortedKeys(kinds) {
		fmt.Fprintf(w, "- **%s** — %s\n", name, kinds[name])
	}
	fmt.Fprintln(w)
}

// renderUniversalPaths derives the cross-tool path map from the tools data.
// For each project_path that appears across multiple tools, list which tools
// read it. This used to be hand-maintained in the JSON; now derived.
func renderUniversalPaths(w io.Writer, doc *projectionDoc) {
	pathReaders := map[string]map[string]bool{} // path → set of tool keys
	addPath := func(path, toolKey string) {
		if pathReaders[path] == nil {
			pathReaders[path] = map[string]bool{}
		}
		pathReaders[path][toolKey] = true
	}
	for toolKey, t := range doc.Tools {
		for _, kind := range t.Kinds {
			for _, p := range kind.ProjectPaths {
				addPath(p, toolKey)
			}
		}
	}
	for toolKey, t := range doc.Watchlist.Tools {
		for _, p := range t.ProjectPaths {
			addPath(p, toolKey)
		}
	}

	// Keep only paths read by 2+ tools
	type universalEntry struct {
		Path  string
		Tools []string
	}
	var universal []universalEntry
	for p, readers := range pathReaders {
		if len(readers) < 2 {
			continue
		}
		toolList := sortedSet(readers)
		universal = append(universal, universalEntry{Path: p, Tools: toolList})
	}
	sort.Slice(universal, func(i, j int) bool {
		if len(universal[i].Tools) != len(universal[j].Tools) {
			return len(universal[i].Tools) > len(universal[j].Tools)
		}
		return universal[i].Path < universal[j].Path
	})

	if len(universal) == 0 {
		return
	}
	fmt.Fprintln(w, "## Universal Paths (Derived)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Paths read by **two or more** tools. Derived from `tools` + `watchlist` project_paths.")
	fmt.Fprintln(w, "Ordered by number of tools that read each path.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Path | # tools | Read by |")
	fmt.Fprintln(w, "|---|---|---|")
	for _, e := range universal {
		fmt.Fprintf(w, "| `%s` | %d | %s |\n", e.Path, len(e.Tools), strings.Join(e.Tools, ", "))
	}
	fmt.Fprintln(w)
}

func renderTools(w io.Writer, tools map[string]toolEntry) {
	if len(tools) == 0 {
		return
	}
	fmt.Fprintln(w, "## Deep-Modeled Tools")
	fmt.Fprintln(w)
	for _, key := range sortedKeys(tools) {
		t := tools[key]
		inCode := ""
		if t.CSAWInCode {
			inCode = " · `csaw_in_code: true`"
		}
		fmt.Fprintf(w, "### %s (`%s`)%s\n\n", t.DisplayName, key, inCode)
		if t.DocsHomepage != "" {
			fmt.Fprintf(w, "- **Docs:** [%s](%s)\n", t.DocsHomepage, t.DocsHomepage)
		}
		fmt.Fprintf(w, "- **Category:** %s · **Status:** %s\n", t.Category, t.Status)
		if t.ScopeNotes != "" {
			fmt.Fprintf(w, "- **Notes:** %s\n", t.ScopeNotes)
		}
		fmt.Fprintln(w)
		if len(t.Kinds) > 0 {
			fmt.Fprintln(w, "| Kind | Project paths | User paths | Confidence |")
			fmt.Fprintln(w, "|---|---|---|---|")
			for _, k := range sortedKeys(t.Kinds) {
				ke := t.Kinds[k]
				fmt.Fprintf(w, "| %s | %s | %s | %s |\n",
					k, codeJoin(ke.ProjectPaths), codeJoin(ke.UserPaths), ke.Confidence)
			}
			fmt.Fprintln(w)
		}
		if mcp, ok := t.Kinds["mcp"]; ok && (mcp.SchemaTopKey != "" || len(mcp.Transports) > 0) {
			fmt.Fprintln(w, "**MCP schema:**")
			fmt.Fprintln(w)
			if mcp.SchemaTopKey != "" {
				fmt.Fprintf(w, "- Top-level key: `%s`\n", mcp.SchemaTopKey)
			}
			if len(mcp.Transports) > 0 {
				fmt.Fprintf(w, "- Transports: %s\n", strings.Join(mcp.Transports, ", "))
			}
			if len(mcp.AuthTypes) > 0 {
				fmt.Fprintf(w, "- Auth: %s\n", strings.Join(mcp.AuthTypes, ", "))
			}
			if len(mcp.EnvVarSub) > 0 {
				fmt.Fprintf(w, "- Env var substitution: %s\n", strings.Join(mcp.EnvVarSub, ", "))
			}
			fmt.Fprintln(w)
		}
	}
}

func renderWatchlist(w io.Writer, wl *watchlistSection) {
	if len(wl.Tools) == 0 {
		return
	}
	fmt.Fprintln(w, "## Watchlist")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "%s\n\n", wl.Description)
	fmt.Fprintln(w, "| Tool | csaw_in_code | Project paths | User paths |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, key := range sortedKeys(wl.Tools) {
		t := wl.Tools[key]
		inCode := "—"
		if t.CSAWInCode {
			inCode = "true"
		}
		fmt.Fprintf(w, "| %s (`%s`) | %s | %s | %s |\n",
			t.DisplayName, key, inCode, codeJoin(t.ProjectPaths), codeJoin(t.UserPaths))
	}
	fmt.Fprintln(w)
}

// --- helpers ---

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedSet(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func codeJoin(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	parts := make([]string, len(items))
	for i, item := range items {
		parts[i] = "`" + item + "`"
	}
	return strings.Join(parts, ", ")
}
